/// Flutter icons Monstera
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Monstera
///      fonts:
///       - asset: fonts/Monstera.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Monstera {
  Monstera._();

  static const _kFontFam = 'Monstera';

  static const IconData monstera = const IconData(0xe800, fontFamily: _kFontFam);
}
